name: Build and deploy Docker images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2.2.1
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        platforms: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
